<?php

namespace Database\Seeders;

use App\Models\Brand_Category;
use Illuminate\Database\Seeder;

class Brand_CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Brand_Categories=[
            [
                'brand_id'=>'1',
                'category_id'=>'1'
            ],
            [
                'brand_id'=>'2',
                'category_id'=>'1'
            ],
            [
                'brand_id'=>'3',
                'category_id'=>'1'
            ],
            [
                'brand_id'=>'4',
                'category_id'=>'2'
            ],
            [
                'brand_id'=>'5',
                'category_id'=>'2'
            ],
            [
                'brand_id'=>'6',
                'category_id'=>'2'
            ],
            [
                'brand_id'=>'7',
                'category_id'=>'2'
            ],
            [
                'brand_id'=>'8',
                'category_id'=>'2'
            ],
            [
                'brand_id'=>'9',
                'category_id'=>'2'
            ],
            [
                'brand_id'=>'10',
                'category_id'=>'3'
            ],
            [
                'brand_id'=>'11',
                'category_id'=>'3'
            ],
            [
                'brand_id'=>'12',
                'category_id'=>'4'
            ],
            [
                'brand_id'=>'13',
                'category_id'=>'4'
            ],
            [
                'brand_id'=>'14',
                'category_id'=>'4'
            ],
            [
                'brand_id'=>'15',
                'category_id'=>'8'
            ],
            [
                'brand_id'=>'16',
                'category_id'=>'6'
            ],
            [
                'brand_id'=>'17',
                'category_id'=>'6'
            ],
            [
                'brand_id'=>'18',
                'category_id'=>'6'
            ],
            [
                'brand_id'=>'19',
                'category_id'=>'6'
            ],
            [
                'brand_id'=>'20',
                'category_id'=>'6'
            ],
            [
                'brand_id'=>'21',
                'category_id'=>'7'
            ],
            [
                'brand_id'=>'22',
                'category_id'=>'7'
            ],
            [
                'brand_id'=>'23',
                'category_id'=>'7'
            ],
            [
                'brand_id'=>'24',
                'category_id'=>'7'
            ],
            [
                'brand_id'=>'25',
                'category_id'=>'7'
            ],
            [
                'brand_id'=>'26',
                'category_id'=>'7'
            ],
            [
                'brand_id'=>'27',
                'category_id'=>'7'
            ],
            [
                'brand_id'=>'28',
                'category_id'=>'8'
            ],
            [
                'brand_id'=>'29',
                'category_id'=>'9'
            ]
        ];
        foreach($Brand_Categories as $Brand_Category){
            Brand_Category::create($Brand_Category);
        }
    }
}
